### ISSUE TITLE
Time change and Third Person

### ISSUE THREAD

**Issue by SilentStormx1** [RCPisAwesome/FiveMRCPAxonCamera#1]
Hey mate, just wondering how I would go about changing two things. First being able to choose a third person view for it (not just first person) and also changing the time and date to Australian Eastern Standard Time from UTC? Would also be awesome to be able to toggle it on/ off with a chat command if its in third person.

**Comment by RCPisAwesome** [comment]
Thanks for the suggestions! I just pushed an update that allows everything you wanted :)
