### ISSUE TITLE
sounds

### ISSUE THREAD

**Issue by timothysahakian** [RCPisAwesome/FiveMRCPAxonCamera#2]
I would like to change the sounds to something more realistic. how can i do that? and if I cant do it could you maybe do it for me?
or could you make it where the sounds are local instead of a URL?

**Comment by RCPisAwesome** [comment]
1. add the file to the resource folder
2. add it as a file to the fxmanifest.lua file e.g. `file "sound.mp3"`
3. change the url on line 19 of the html file to the filename e.g. `var beep = new Howl({src: ["sound.mp3"]});`
Should work with any audio file but just in case it's probably better to use a .wav file or change the file to a .wav

**Comment by timothysahakian** [comment]
sweeet thank you it worked!! also do you have a discord i can join?

**Comment by RCPisAwesome** [comment]
yes, I don't use it much though. https://discord.com/invite/vzJSHuM
